import type { Metadata } from 'next';

import { Toaster } from '@/components/ui/toaster';
import '@/config/globals.css';
import Footer from '@/layouts/Footer';
import Header from '@/layouts/Header';
import { ThemeProvider } from '@/layouts/theme/Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='h-full scroll-my-20 scroll-smooth'
      suppressHydrationWarning
    >
      <body className='flex min-h-screen flex-col bg-background font-pretendard'>
        <ThemeProvider defaultTheme='dark'>
          <Header />
          <main className='relative block pt-header'>{children}</main>
          <Footer />
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
