import type { Metadata } from 'next';

import { ThemeProvider } from '@/layouts/theme/Provider';
import '@/lib/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='font-pretendard flex min-h-screen flex-col'>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
